@REQ_TACS-1164
Feature: ROBOT-HU-ENGAGE- SmokeTest robot

	@TEST_TACS-1140 @TESTSET_TACS-742 @TESTSET_TACS-1162 @ENGAGE.REG.REGRESION @ENGAGE.REG.SMOKEARCHIVOSAPOYO @ENGAGE.REG.SMOKETEST
	Scenario: ROBOT-TC-ENGAGE-WEB - SmokeTest archivos de apoyo
		Given verificar lectura de archivos de apoyo
	@TEST_TACS-1139 @TESTSET_TACS-742 @TESTSET_TACS-1162 @ENGAGE.REG.REGRESION @ENGAGE.REG.SMOKESESAMO @ENGAGE.REG.SMOKETEST
	Scenario: ROBOT-TC-ENGAGE-WEB - SmokeTest sesamo
		Given verifica conexion a sesamo
	@TEST_TACS-1138 @TESTSET_TACS-742 @TESTSET_TACS-1162 @ENGAGE.REG.REGRESION @ENGAGE.REG.SMOKELOGIN @ENGAGE.REG.SMOKETEST
	Scenario: ROBOT-TC-ENGAGE-WEB - SmokeTest login
		Given ingresar a Engage web
		When selecciona el perfil deseado
		And finalizo la sesion del usuario ingresado
	@TEST_TACS-1137 @TESTSET_TACS-742 @TESTSET_TACS-1162 @ENGAGE.REG.REGRESION @ENGAGE.REG.SMOKECARGAAMBIENTE @ENGAGE.REG.SMOKETEST
	Scenario: ROBOT-TC-ENGAGE-WEB - SmokeTest carga de ambiente
		Given ingresar a ambiente Engage web
